def cylinderFormula():

    # This file was generated by the Tkinter Designer by Parth Jadhav
    # https://github.com/ParthJadhav/Tkinter-Designer

    from main_menu import openShapesWindow
    from pathlib import Path
    from math import pi
    # from tkinter import *
    # Explicit imports to satisfy Flake8
    from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"Calculator GUI/build/assets/frame2")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    def cylinderRadius(height, radius):
        cylinderDiameter = radius * 2
        cylinderLateralArea = 2 * pi * radius * height
        cylinderSurfaceArea = (2 * pi * radius * height) + (2 * pi * (radius ** 2))
        cylinderVolume = pi * (radius ** 2) * height

        return cylinderLateralArea, cylinderSurfaceArea, cylinderVolume, cylinderDiameter

    def calculateCylinder():
        try:
            # Get the input values from entry widgets
            height = float(entry_2.get())
            radius = float(entry_1.get())

            # Calculate using cylinderRadius function
            lateral_area, surface_area, volume, cylinder_diameter = cylinderRadius(height, radius)

            with open("cylinder_results.txt", "w") as file:
                file.write(f"Lateral Area: {lateral_area}\nSurface Area: {surface_area}\nVolume: {volume}\nCylinder Diameter: {cylinder_diameter}")
            
            # Format the results to one decimal point
            lateral_area = "{:.1f}".format(lateral_area)
            surface_area = "{:.1f}".format(surface_area)
            volume = "{:.1f}".format(volume)
            cylinder_diameter = "{:.1f}".format(cylinder_diameter)

            # Display the results in the text widget
            result_text = f"Lateral Area: {lateral_area}\nSurface Area: {surface_area}\nVolume: {volume}\nCylinder Diameter: {cylinder_diameter}"
            result_display.config(state="normal")
            result_display.delete(1.0, "end")
            result_display.insert("end", result_text)
            result_display.config(state="disabled")

        except ValueError:
            # Handle invalid input (non-numeric)
            result_display.config(state="normal")
            result_display.delete(1.0, "end")
            result_display.insert("end", "Invalid input: Please enter a number.")
            result_display.config(state="disabled")

    window = Tk()

    window.geometry("862x519")
    window.configure(bg = "#016938")


    canvas = Canvas(
        window,
        bg = "#016938",
        height = 519,
        width = 862,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        333.0,
        33.0,
        anchor="nw",
        text="Cylinder Calculator",
        fill="#FCFCFC",
        font=("Roboto Bold", 24 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        142.0,
        175.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=46.0,
        y=138.0,
        width=192.0,
        height=72.0
    )

    canvas.create_text(
        69.0,
        95.0,
        anchor="nw",
        text="Input Radius",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        142.0,
        295.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=46.0,
        y=258.0,
        width=192.0,
        height=72.0
    )

    canvas.create_text(
        67.0,
        218.0,
        anchor="nw",
        text="Input Height",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )




    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=calculateCylinder,
        relief="flat"
    )
    button_1.place(
        x=363.0,
        y=436.0,
        width=128.0,
        height=43.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(), openShapesWindow()),
        relief="flat"
    )
    button_2.place(
        x=757.0,
        y=25.0,
        width=68.0,
        height=43.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        436.0,
        245.0,
        image=image_image_1
    )

    result_display = Text(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        wrap="word",
        font=("Inter", 13)
    )
    result_display.place(
        x=600,
        y=432.0,
        width=200.0,
        height=58.0
    )

    window.resizable(False, False)
    window.mainloop()
